import { NextRequest } from 'next/server';

// Self-service per-visitor provisioning. Each browser session receives an
// isolated party set on the connected DevNet synchronizer. Local sandbox mode
// falls back to the static ledger-config.json generated by bootstrap.sh.

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 30;

const ENABLED = process.env.CLOAKRFQ_SESSION_PROVISIONING === '1';
const TARGET = (process.env.CLOAKRFQ_LEDGER_TARGET ?? '').replace(/\/$/, '');
const USER_ID = process.env.CLOAKRFQ_LEDGER_USER_ID ?? '6';
const PKG = process.env.CLOAKRFQ_PACKAGE_REF ?? '#cloakrfq-contracts-v2';
const PARTY_NAMESPACE = process.env.CLOAKRFQ_PARTY_NAMESPACE ?? '';
const PROVISIONING_VERSION = 'v2';
const HAS_OIDC = Boolean(process.env.CLOAKRFQ_OIDC_CLIENT_SECRET);
const ROLES: Record<string, string> = {
  seller: 'cloakrfqSeller', funderA: 'cloakrfqFunderA', funderB: 'cloakrfqFunderB', funderC: 'cloakrfqFunderC',
  compliance: 'cloakrfqCompliance', risk: 'cloakrfqRisk', coordinator: 'cloakrfqCoordinator', auditor: 'cloakrfqAuditor', outsider: 'cloakrfqOutsider', tokenAdmin: 'cloakrfqTokenAdmin',
};

type SessionConfig = {
  jsonApiUrl: string;
  packageRef: string;
  userId: string;
  parties: Record<string, string>;
};

async function api(origin: string, method: string, path: string, body?: unknown): Promise<{ status: number; json: any }> {
  const transient = new Set([429, 502, 503, 504]);
  for (let attempt = 0; attempt < 5; attempt++) {
    const response = await fetch(`${origin}${path}`, {
      method,
      headers: body !== undefined ? { 'Content-Type': 'application/json' } : undefined,
      body: body !== undefined ? JSON.stringify(body) : undefined,
      cache: 'no-store',
    });
    const text = await response.text();
    let json: any = {};
    try { json = text ? JSON.parse(text) : {}; } catch { json = {}; }
    if (!transient.has(response.status) || attempt === 4) return { status: response.status, json };
    await pause(750 * (attempt + 1));
  }
  throw new Error(`Ledger proxy request exhausted retries: ${method} ${path}`);
}

const sessionCache = new Map<string, SessionConfig>();
let inflight = 0;
const pause = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const partyHint = (base: string, sid: string) => `${base}-${PROVISIONING_VERSION}-${sid}`;

async function getSynchronizerId(origin: string): Promise<string> {
  const { status, json } = await api(origin, 'GET', '/v2/state/connected-synchronizers');
  const connected = json?.connectedSynchronizers ?? [];
  const synchronizer = connected.find((item: any) => item.permission === 'PARTICIPANT_PERMISSION_SUBMISSION') ?? connected[0];
  if (status !== 200 || !synchronizer?.synchronizerId) throw new Error(`No connected Canton synchronizer is available (HTTP ${status})`);
  return String(synchronizer.synchronizerId);
}


async function waitForParty(origin: string, party: string, synchronizerId: string): Promise<void> {
  for (let attempt = 0; attempt < 10; attempt++) {
    const path = `/v2/state/connected-synchronizers?party=${encodeURIComponent(party)}`;
    const { status, json } = await api(origin, 'GET', path);
    const active = status === 200 && (json?.connectedSynchronizers ?? []).some((item: any) =>
      item.synchronizerId === synchronizerId && item.permission === 'PARTICIPANT_PERMISSION_SUBMISSION');
    if (active) return;
    await pause(750);
  }
  throw new Error(`Party did not become active on the selected synchronizer: ${party.split('::')[0]}`);
}


async function grantCanActAs(origin: string, party: string): Promise<void> {
  const { status } = await api(origin, 'POST', `/v2/users/${encodeURIComponent(USER_ID)}/rights`, {
    userId: USER_ID,
    rights: [{ kind: { CanActAs: { value: { party } } } }],
  });
  if (status !== 200) throw new Error(`CanActAs grant failed for ${party.split('::')[0]} (HTTP ${status})`);
}

async function verifyCanActAs(origin: string, parties: string[]): Promise<void> {
  const { status, json } = await api(origin, 'GET', `/v2/users/${encodeURIComponent(USER_ID)}/rights`);
  if (status !== 200) throw new Error(`User rights verification failed (HTTP ${status})`);

  const authorized = new Set<string>((json?.rights ?? []).flatMap((right: any) => {
    const party = right?.kind?.CanActAs?.value?.party;
    return party ? [String(party)] : [];
  }));
  const missing = parties.filter((party) => !authorized.has(party));
  if (missing.length > 0) {
    throw new Error(`CanActAs verification failed for: ${missing.map((party) => party.split('::')[0]).join(', ')}`);
  }
}

async function allocateParty(origin: string, hint: string, synchronizerId: string, role: string): Promise<string> {
  for (let attempt = 0; attempt < 6; attempt++) {
    const { status, json } = await api(origin, 'POST', '/v2/parties', {
      partyIdHint: hint,
      synchronizerId,
    });
    const party = json?.partyDetails?.party;
    if (status === 200 && party) return String(party);
    const cause = String(json?.cause ?? json?.code ?? 'unknown error');
    if (status === 400) {
      if (cause.includes('Party already exists') && PARTY_NAMESPACE) return `${hint}::${PARTY_NAMESPACE}`;
      if (attempt < 5) { await pause(1250); continue; }
    }
    throw new Error(`Party allocation failed for ${role} (HTTP ${status}): ${cause}`);
  }
  throw new Error(`Party allocation failed for ${role}`);
}
async function provision(origin: string, sid: string): Promise<SessionConfig> {
  const synchronizerId = await getSynchronizerId(origin);
  const parties: Record<string, string> = {};

  for (const [role, base] of Object.entries(ROLES)) {
    const party = await allocateParty(origin, partyHint(base, sid), synchronizerId, role);
    parties[role] = party;
    await waitForParty(origin, party, synchronizerId);
    await grantCanActAs(origin, party);
  }
  await verifyCanActAs(origin, Object.values(parties));
  return { jsonApiUrl: TARGET, packageRef: PKG, userId: USER_ID, parties };
}

export async function GET(req: NextRequest) {
  if (!ENABLED || !TARGET || !HAS_OIDC) return Response.json({ enabled: false });
  const sid = (req.nextUrl.searchParams.get('sid') || '').replace(/[^a-zA-Z0-9]/g, '').slice(0, 24);
  if (!sid) return Response.json({ error: 'missing sid' }, { status: 400 });

  const cached = sessionCache.get(sid);
  if (cached) return Response.json(cached);
  if (inflight > 6) return Response.json({ error: 'busy, retry' }, { status: 429 });

  inflight++;
  try {
    const config = await provision(req.nextUrl.origin, sid);
    sessionCache.set(sid, config);
    return Response.json(config);
  } catch (error) {
    return Response.json({ error: String(error) }, { status: 502 });
  } finally {
    inflight--;
  }
}
